{{- if .Values.ingress.enabled -}}
{{- $masterFullName := include "geoserver.master.fullname" . -}}
{{- $masterSvcPort := .Values.master.service.port -}}
{{- $slaveFullName := include "geoserver.slave.fullname" . -}}
{{- $slaveSvcPort := .Values.slave.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.host }}
  {{- if .tlsSecretName }}
  tls:
    - hosts:
        - {{ .name | quote }}
      secretName: {{ .tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ .paths.master.path }}
            {{- if and .paths.master.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .paths.master.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $masterFullName }}
                port:
                  number: {{ $masterSvcPort }}
              {{- else }}
              serviceName: {{ $masterFullName }}
              servicePort: {{ $masterSvcPort }}
              {{- end }}
          - path: {{ .paths.slave.path }}
            {{- if and .paths.slave.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .paths.slave.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $slaveFullName }}
                port:
                  number: {{ $slaveSvcPort }}
              {{- else }}
              serviceName: {{ $slaveFullName }}
              servicePort: {{ $slaveSvcPort }}
              {{- end }}
  {{- end }}
{{- end }}
