{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.slave.fullname" . }}
  labels:
    {{- include "geoserver.slave.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.slave.service.port }}
      targetPort: 8080
      protocol: TCP
      name: tcp-{{ .Values.slave.service.port }}
  selector:
    {{- include "geoserver.slave.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.slave.fullname" . }}-hl
  labels:
    {{- include "geoserver.slave.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.slave.service.port }}
      targetPort: 8080
      protocol: TCP
      name: tcp-{{ .Values.slave.service.port }}
  selector:
    {{- include "geoserver.slave.selectorLabels" . | nindent 4 }}
{{- end }}