apiVersion: v2
name: geoserver
version: 1.0.0
description: |-
  GeoServer is an open source server for sharing geospatial data. 
  Designed for interoperability, it publishes data from any major spatial data source using open standards
type: application
keywords:
  - GIS
  - FOSS4G
  - webmap
  - WMS
  - WFS
  - WCS
home: https://geoserver.org/
sources:
  - https://github.com/geoserver/geoserver
  - https://github.com/nds-cprm/geoserver-oci
maintainers:
  - name: Carlos Eduardo Mota
    email: carlos.mota@sgb.gov.br
icon: "https://geoserver.org/img/geoserver-logo.png"
appVersion: "testing"
dependencies:
  - name: activemq-classic
    version: "0.1.0"
    # repository: "https://nds-cprm.github.io/helm-charts/"
    repository: "file:///home/mota/vscode/helm-charts/charts/activemq-classic"
    alias: activemq
    condition: cluster.enabled
