apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geoserver.master.fullname" . }}
  labels:
    {{- include "geoserver.master.labels" . | nindent 4 }}
spec:
  {{- if not .Values.master.autoscaling.enabled }}
  replicas: {{ .Values.master.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "geoserver.master.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with .Values.master.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "geoserver.master.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "geoserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.master.podSecurityContext | nindent 8 }}
      volumes:
        {{- if .Values.master.pvc.enabled }}
        - name: geoserver-data
          persistentVolumeClaim:
            claimName:  {{ include "geoserver.master.fullname" . }}
        {{- end }}
        {{- with .Values.master.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.master.extraHosts }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.master.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp-{{ .Values.master.service.port }}
              containerPort: {{ .Values.master.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "geoserver.master.fullname" . }}          
          {{- with .Values.master.initContainers }}
          initContainers:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.master.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            exec:
              command: 
                - curl 
                - "-fs" 
                - http://localhost:{{ .Values.master.service.port }}{{ .Values.master.config.contextPath | default "/geoserver" }}
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
      {{- with .Values.master.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
